version: '3'

services:
  nginx_proxy:
    container_name: nginx_proxy
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    networks:
        - external_nginx_proxy
    volumes:
        - ./server.conf:/etc/nginx/conf.d/server.conf:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./certs:/etc/nginx/certs
    logging:
        options:
            max-size: "1m"
            max-file: "1"
    # restart: always

networks:
    external_nginx_proxy:
        external: true
